-- Drop the OWNER3 table.
DROP TABLE 		owner3 				CASCADE CONSTRAINTS;
-- Drop the PROPERTY3 table.
DROP TABLE 		property3 			CASCADE CONSTRAINTS;
-- Drop the OWNER_HISTORY3 table.
DROP TABLE 		owner_history3 		CASCADE CONSTRAINTS;

DROP TABLE 		assessment_history3 CASCADE CONSTRAINTS;

DROP TABLE		ZONE3 				CASCADE CONSTRAINTS;

DROP TABLE 		property_type3 		CASCADE CONSTRAINTS;